services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/healthcheck?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - healthcheck
    restart: always

  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=healthcheck
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - healthcheck
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  healthcheck:
    driver: bridge
