services:
  app:
    build:
      context: .
      dockerfile: ./local/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    networks:
      - health-check

  database:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - health-check
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  health-check:
    driver: bridge

volumes:
  postgres-data:
