name: Publish Docker
permissions: read-all
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env.example file
        run: |
          echo "NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID=" > .env.example
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.example
          echo "NEXTAUTH_SECRET=abcdefg" >> .env.example
          echo "GITHUB_ID=" >> .env.example
          echo "GITHUB_SECRET=" >> .env.example
          echo "DATABASE_URL=\"postgresql://user:password@localhost:5432/healthcheck?schema=public\"" >> .env
          echo "NEXT_PUBLIC_REPO_LIMIT=10" >> .env.example
          echo "NEXT_PUBLIC_GITHUB_CACHE=24" >> .env.example
      - name: npm install and build
        run: |
          npm ci
          echo "NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID=${{ secrets.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID }}" >> .env
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: artifacts
          path: prod/
  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: version dockerfile
        uses: docker/setup-buildx-action@v3
      - name: log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/eddiehubcommunity/healthcheck:v${{ steps.package-version.outputs.current-version}}
            ghcr.io/eddiehubcommunity/healthcheck:latest
